apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
spec:
    replicas: 4
    selector:
        matchLabels:
            component: server
    template:
        metadata:
            labels:
                component: server
        spec:
            containers:
                - name: server
                  image: darshandcode/server:v1
                  ports:
                    - containerPort: 5000
                  env:
                    - name: RDESI_HOST
                      value: redis-cluster-ip
                    - name: RESDIS_PORT
                      value: "6379"
                    - name: pguser
                      value: postgres
                    - name: PGHOST
                      value: postgres-cluster-ip
                    - name: PGPORT
                      value: "5432"
                    - name: PGDATABASE
                      value: postgres
                    - name: PGPASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: pgpassword
                            key: PGPASSWORD
                      
        
